controller_manager_ns: controller_manager
controller_list:
  - name: arm/arm_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - zhixianmove
      - zhuan1
      - zhuan2
      - zhuan3
      - zhuan4
      - zhuan5
