arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: zhixianmove
    pid: {p: 800, i: 40, d: 180}
  
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: zhuan1
    pid: {p: 200, i: 20, d: 40}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: zhuan2
    pid: {p: 50, i: 3, d: 10}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: zhuan3
    pid: {p: 30, i: 0.5, d: 5}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: zhuan4
    pid: {p: 20, i: 0.2, d: 2}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: zhuan5
    pid: {p: 1.0, i: 1.0, d: 0.0}
  #
  #gazebo_ros_control:
   # pid_gains:
    #  zhixianmove:
     #   p: 10.0
      #  d: 1.0
      #  i: 0.1