# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

 # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: zhixianmove
    pid: {p: 20.0, i: 0.01, d: 1.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: zhuan1
    pid: {p: 10.0, i: 0.01, d: 1.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: zhuan2
    pid: {p: 10.0, i: 0.01, d: 1.0}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: zhuan3
    pid: {p: 10.0, i: 0.01, d: 1.0}
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: zhuan4
    pid: {p: 10.0, i: 0.01, d: 1.0}
  joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: zhuan5
    pid: {p: 0.0, i: 0.0, d: 0.0}